name: "Post-Run Action"
description: "A simple GitHub action that enables running post-run tasks, once a workflow job has ended."

inputs:
  command:
    description: "A command that needs to be run."
    required: true
    default: echo "This is a post-action command..."

runs:
  using: node12
  main: dist/main/index.js
  post: dist/post/index.js
